#:schema https://docs.jj-vcs.dev/latest/config-schema.json

[ui]
default-command = ["util", "exec", "jjui"]
pager = "delta"
diff-formatter = ":git"  # Required by `delta`

[working-copy]
eol-conversion = "input"

[aliases]
prompt_log = ["log", "--ignore-working-copy", "--no-graph", "--no-pager"]

[template-aliases]
# Conflict: 
# Divergent: 󰙁
# Hidden: 󰈉
# Immutable: 
# Needs description: 
#
# Using `label` causes rest of the prompt to be white. So, attach `label` to
# all symbols in order to force colors.
prompt_symbols = """
concat(
    if(conflict, label('conflict', '\uf467 '), ''),
    if(divergent, label('normal', '\U000f0641 '), ''),
    if(hidden, label('normal', '\U000f0209 '), ''),
    if(immutable, label('normal', '\uf023 ')),
    if(!empty && description == '', label('normal', '\uf448 '), '')
)
"""

[revset-aliases]
'closest_named_change(to)' = """
coalesce(
    heads(::to & (bookmarks() | remote_bookmarks() | tags())),
    heads(to:: & (bookmarks() | remote_bookmarks() | tags())),
    trunk()
)
"""
'non_empty(from, to)' = "from..to & (~empty() | merges())"

[colors]
normal = "black"
