#:schema https://jj-vcs.github.io/jj/latest/config-schema.json

[ui]
default-command = ["util", "exec", "jjui"]
pager = "delta"
diff-formatter = ":git"  # Required by `delta`
# `delta` cannot properly render merge conflicts through `jj diff` because the
# `:git` diff formatter does not produce combined diffs in such cases
#
# See https://github.com/jj-vcs/jj/discussions/4690#discussioncomment-14098877
conflict-marker-style = "git"

[working-copy]
eol-conversion = "input"

[aliases]
prompt_log = ["log", "--ignore-working-copy", "--no-graph", "--no-pager"]

[template-aliases]
# Needs description: 
# Conflict: 
prompt_symbols = """
concat(
    if(conflict, label('conflict', '\uf467'), ''),
    if(!empty && description == '', '\uf448', '')
)
"""
