#:schema https://docs.jj-vcs.dev/latest/config-schema.json

[ui]
default-command = ["util", "exec", "jjui"]
pager = "delta"
diff-formatter = ":git"  # Required by `delta`

[working-copy]
eol-conversion = "input"

[aliases]
prompt_log = ["log", "--ignore-working-copy", "--no-graph", "--no-pager"]

[template-aliases]
# Needs description: 
# Conflict: 
prompt_symbols = """
concat(
    if(conflict, label('conflict', '\uf467'), ''),
    if(!empty && description == '', '\uf448', '')
)
"""
