#:schema https://mise.jdx.dev/schema/mise.json

# Remember that all entries in this global config should be valid for all
# environments/platforms

min_version = "2026.7.4"

[settings]
dotfiles.root = "~/.config/mise/rc"
dotfiles.default_mode = "copy"
use_versions_host_track = false

[shell_alias]
lg = "lazygit"
y = "yazi"

[dotfiles]
"~/.config/git/ignore" = {}
"~/.gitconfig" = {}
