variables:
  dotdrop_root: "{{@@ _dotdrop_dotpath @@}}/.."
  scripts_dir: "{{@@ dotdrop_root @@}}/scripts"
actions:
  winget_install: pwsh -nop "{{@@ scripts_dir @@}}/install_pkg.ps1" {0} {1}
config:
  banner: false
  dotpath: rc
  force_chmod: true
dotfiles:
  f_gitconfig:
    src: .gitconfig
    dst: ~/.gitconfig
  f_git_ignore:
    src: .config/git/ignore
    dst: ~/.config/git/ignore
  f_profile.ps1:
    src: windows/profile.ps1
    dst: "{{@@ env['UserProfile'] @@}}/Documents/PowerShell/Microsoft.PowerShell_profile.ps1"
    actions:
      - winget_install JanDeDobbeleer.OhMyPosh oh-my-posh
  f_winterm_settings.json:
    src: windows/settings.json
    dst: "{{@@ env['LocalAppData'] @@}}/Packages/Microsoft.WindowsTerminal_8wekyb3d8bbwe/LocalState/settings.json"
    link: absolute
    actions:
      - winget_install Microsoft.WindowsTerminal wt
profiles:
  windows:
    dotfiles:
      - f_gitconfig
      - f_git_ignore
      - f_profile.ps1
      - f_winterm_settings.json
