variables:
  dotdrop_root: "{{@@ _dotdrop_dotpath @@}}/.."
  scripts_dir: "{{@@ dotdrop_root @@}}/scripts"

  # To be overriden locally
  git_name: ""
  git_email: ""
actions:
  setup_ps: pwsh -nop "{{@@ scripts_dir @@}}/setup_ps.ps1"
  winget_install: pwsh -nop "{{@@ scripts_dir @@}}/install_pkg.ps1" {0} {1}
config:
  banner: false
  dotpath: rc
  import_variables:
    - .local_vars.yaml:optional
dotfiles:
  f_gitconfig:
    src: gitconfig
    dst: ~/.gitconfig
  f_gitignore_global:
    src: gitignore_global
    dst: ~/.gitignore_global
  f_profile.ps1:
    src: profile.ps1
    dst: "{{@@ env['UserProfile'] @@}}/Documents/PowerShell/Microsoft.PowerShell_profile.ps1"
    actions:
      - setup_ps
  f_winterm_settings.json:
    src: winterm-settings.json
    dst: "{{@@ env['LocalAppData'] @@}}/Packages/Microsoft.WindowsTerminal_8wekyb3d8bbwe/LocalState/settings.json"
    actions:
      - winget_install wt Microsoft.WindowsTerminal
  f_zprofile:
    src: zprofile
    dst: ~/.zprofile
  f_zshrc:
    src: zshrc
    dst: ~/.zshrc
  f_p10k.zsh:
    src: p10k.zsh
    dst: ~/.p10k.zsh
profiles:
  linux:
    dotfiles:
      - f_gitconfig
      - f_gitignore_global
      - f_zprofile
      - f_zshrc
      - f_p10k.zsh
  windows:
    dotfiles:
      - f_gitconfig
      - f_gitignore_global
      - f_profile.ps1
      - f_winterm_settings.json
