variables:
  dotdrop_root: "{{@@ _dotdrop_dotpath @@}}/.."
  scripts_dir: "{{@@ dotdrop_root @@}}/scripts"

  # To be overriden locally
  git_name: ""
  git_email: ""
actions:
  pre:
    setup_windows: pwsh -nop "{{@@ dotdrop_root @@}}/setup.ps1"
config:
  banner: false
  dotpath: rc
  import_variables:
    - .local_vars.yaml:optional
dotfiles:
  f_gitconfig:
    src: gitconfig
    dst: ~/.gitconfig
  f_gitignore_global:
    src: gitignore_global
    dst: ~/.gitignore_global
  f_profile.ps1:
    src: profile.ps1
    dst: "{{@@ env['UserProfile'] @@}}/Documents/PowerShell/Microsoft.PowerShell_profile.ps1"
  f_winterm_settings.json:
    src: winterm-settings.json
    dst: "{{@@ env['LocalAppData'] @@}}/Packages/Microsoft.WindowsTerminal_8wekyb3d8bbwe/LocalState/settings.json"
profiles:
  linux:
    dotfiles:
      - f_gitconfig
      - f_gitignore_global
  windows:
    dotfiles:
      - f_gitconfig
      - f_gitignore_global
      - f_profile.ps1
      - f_winterm_settings.json
    actions:
      - setup_windows
