variables:
  dotdrop_root: "{{@@ _dotdrop_dotpath @@}}/.."
  scripts_dir: "{{@@ dotdrop_root @@}}/scripts"
actions:
  setup_sh: "{{@@ scripts_dir @@}}/setup.sh"
  winget_install: pwsh -nop "{{@@ scripts_dir @@}}/install_pkg.ps1" {0} {1}
config:
  banner: false
  dotpath: rc
  force_chmod: true
  import_variables:
    - .local_vars.yaml:optional
dotfiles:
  # git
  f_gitconfig:
    src: gitconfig
    dst: ~/.gitconfig
  f_git_ignore:
    src: config/git/ignore
    dst: ~/.config/git/ignore

  # Windows
  f_profile.ps1:
    src: profile.ps1
    dst: "{{@@ env['UserProfile'] @@}}/Documents/PowerShell/Microsoft.PowerShell_profile.ps1"
    actions:
      - winget_install JanDeDobbeleer.OhMyPosh oh-my-posh
  f_winterm_settings.json:
    src: winterm-settings.json
    dst: "{{@@ env['LocalAppData'] @@}}/Packages/Microsoft.WindowsTerminal_8wekyb3d8bbwe/LocalState/settings.json"
    actions:
      - winget_install Microsoft.WindowsTerminal wt

  # WSL
  f_wsl.conf:
    src: etc/wsl.conf
    dst: /etc/wsl.conf

  # zsh
  f_zprofile:
    src: zprofile
    dst: ~/.zprofile
  f_zshrc:
    src: zshrc
    dst: ~/.zshrc
  f_p10k.zsh:
    src: p10k.zsh
    dst: ~/.p10k.zsh

  # fd
  f_fd_ignore:
    src: config/fd/ignore
    dst: ~/.config/fd/ignore
  f_fd:
    src: /usr/bin/fdfind
    dst: ~/.local/bin/fd
    link: absolute

  # ranger
  f_ranger_commands.py:
    src: config/ranger/commands.py
    dst: ~/.config/ranger/commands.py
  f_ranger_rc.conf:
    src: config/ranger/rc.conf
    dst: ~/.config/ranger/rc.conf
  f_ranger_scope.sh:
    src: config/ranger/scope.sh
    dst: ~/.config/ranger/scope.sh
    chmod: 755

  f_global.ctags:
    src: ctags.d/global.ctags
    dst: ~/.ctags.d/global.ctags
  f_lazygit_config.yml:
    src: config/lazygit/config.yml
    dst: ~/.config/lazygit/config.yml
  f_bat:
    src: /usr/bin/batcat
    dst: ~/.local/bin/bat
    link: absolute
profiles:
  linux:
    dotfiles:
      - f_gitconfig
      - f_git_ignore
      - f_zprofile
      - f_zshrc
      - f_p10k.zsh
      - f_fd_ignore
      - f_fd
      - f_ranger_commands.py
      - f_ranger_rc.conf
      - f_ranger_scope.sh
      - f_global.ctags
      - f_lazygit_config.yml
      - f_bat
    actions:
      - setup_sh
  wsl-root:
    dotfiles:
      - f_wsl.conf
  windows:
    dotfiles:
      - f_gitconfig
      - f_git_ignore
      - f_profile.ps1
      - f_winterm_settings.json
