#:schema https://mise.jdx.dev/schema/mise.json

[hooks.postinstall]
shell = "bash -c"
run = """
if [[ -n "$MISE_INSTALLED_TOOLS" ]]; then
    eval "$(~/.local/bin/mise activate bash)"

    misecompsync_up="$(echo "$MISE_INSTALLED_TOOLS" |
        mise x jq -- jq -r 'any(.[]; .name == "mise-completions-sync")')"

    # If `mise-completions-sync` was upgraded, regenerate all completions as
    # new ones could have been added
    if [[ "$misecompsync_up" = true ]]; then
        misecompsync --shell zsh
    else
        misecompsync --shell zsh --new-only
    fi
fi
"""

[settings]
color_theme = "catppuccin"
experimental = true
lockfile = true
lockfile_platforms = ["linux-x64"]
use_versions_host_track = false
