#:schema https://mise.jdx.dev/schema/mise.json

[hooks.postinstall]
shell = "bash -c"
run = """
if [[ -n "$MISE_INSTALLED_TOOLS" ]]; then
    eval "$(~/.local/bin/mise activate bash)"

    installed_tools="$(echo "$MISE_INSTALLED_TOOLS" |
        mise x jq -- jq -r '.[].name')"
    for tool in "$installed_tools"; do
        if [[ "$tool" = "mise-completions-sync" ]]; then
            misecompsync --shell zsh
            exit
        fi
    done

    echo "$installed_tools" | xargs --no-run-if-empty misecompsync --shell zsh
fi
"""

[settings]
color_theme = "catppuccin"
experimental = true
lockfile = true
lockfile_platforms = ["linux-x64"]
use_versions_host_track = false
