#:schema https://mise.jdx.dev/schema/mise.json

[hooks.postinstall]
shell = "bash -c"
run = """
if [[ -n "$MISE_INSTALLED_TOOLS" ]]; then
    mise x mise-completions-sync -- misecompsync -s zsh --new-only
fi
"""

[settings]
color_theme = "catppuccin"
experimental = true
lockfile = true
lockfile_platforms = ["linux-x64"]
use_versions_host_track = false
