#:schema https://mise.jdx.dev/schema/mise.json

[tool_alias]
7zip = "github:ip7z/7zip"
dotdrop = "pipx:dotdrop"
ipython = "pipx:ipython"
mergiraf = "cargo:mergiraf"
mise-completions-sync = "cargo:mise-completions-sync"
patool = "pipx:patool"
ratarmount = "pipx:ratarmount"
tldr = "cargo:tealdeer"
trash-cli = "pipx:trash-cli"

[tools]
7zip = "26"
bat = "latest"
delta = "latest"
fd = "latest"
cargo-binstall = "latest"
fzf = "latest"
jj = "latest"
jjui = "latest"
lazygit = "latest"
lua = "5.5"
mergiraf = "latest"
mise-completions-sync = "latest"
neovim = "latest"
ripgrep = "latest"
node = "latest"
rust = "latest"
tree-sitter = "latest"
uv = "latest"
vivid = "latest"
"pipx:pynvim" = "latest"

[tools.dotdrop]
version = "latest"
postinstall = """
curl -fsSLo ~/.zsh-complete/_dotdrop \
    "https://raw.githubusercontent.com/deadc0de6/dotdrop/refs/tags/v${MISE_TOOL_INSTALL_PATH##*/}/completion/_dotdrop-completion.zsh"
"""

[tools.eza]
version = "latest"
postinstall = """
curl --output-dir ~/.zsh-complete -fsSLO \
    "https://raw.githubusercontent.com/eza-community/eza/refs/tags/v${MISE_TOOL_INSTALL_PATH##*/}/completions/zsh/_eza"

mkdir -p ~/.config/eza
ln -sf \
    ~/.cache/antidote/catppuccin/eza/themes/mocha/catppuccin-mocha-lavender.yml \
    ~/.config/eza/theme.yml
"""

[tools.ipython]
version = "latest"
extras = "all"
postinstall = """
"$MISE_TOOL_INSTALL_PATH/ipython/bin/register-python-argcomplete" ipython > ~/.zsh-complete/_ipython
"""

[tools.patool]
version = "latest"
extras = "argcompletion"
postinstall = """
"$MISE_TOOL_INSTALL_PATH/patool/bin/register-python-argcomplete" patool > ~/.zsh-complete/_patool
"""

[tools.ratarmount]
version = "latest"
uvx_args = "--with argcomplete"
postinstall = """
"$MISE_TOOL_INSTALL_PATH/ratarmount/bin/register-python-argcomplete" ratarmount > ~/.zsh-complete/_ratarmount
"""

[tools.tldr]
version = "latest"
postinstall = """
curl -fsSLo ~/.zsh-complete/_tldr \
    "https://github.com/tealdeer-rs/tealdeer/releases/download/v${MISE_TOOL_INSTALL_PATH##*/}/completions_zsh"
"""

[tools.trash-cli]
version = "latest"
extras = "completion"
postinstall = """
cmds=(trash-empty trash-list trash-restore trash-put trash)
for cmd in ${cmds[@]}; do
    $cmd --print-completion zsh > ~/.zsh-complete/_$cmd
done
"""

[tools.usage]
version = "latest"
postinstall = "usage --completions zsh > ~/.zsh-complete/_usage"

[tools.yazi]
version = "latest"
postinstall = """
ya pkg install

cd "$MISE_TOOL_INSTALL_PATH"
cp */completions/{_ya,_yazi} ~/.zsh-complete
"""

[tools.zoxide]
version = "latest"
postinstall = """
curl --output-dir ~/.zsh-complete -fsSLO \
    "https://raw.githubusercontent.com/ajeetdsouza/zoxide/refs/tags/v${MISE_TOOL_INSTALL_PATH##*/}/contrib/completions/_zoxide"
"""
