#:schema https://mise.jdx.dev/schema/mise.json

[tool_alias]
dotdrop = "pipx:dotdrop"
ipython = "pipx:ipython"
mergiraf = "cargo:mergiraf"
ouch = "github:ouch-org/ouch" # cargo doesn't have shell completions
ratarmount = "pipx:ratarmount"
tldr = "cargo:tealdeer"
trash-cli = "pipx:trash-cli"

# Latest release v1.9.4 is several years old and missing several fixes
ranger = "pipx:git+https://github.com/ranger/ranger.git"

[tools]
cargo-binstall = "latest"
fzf = "latest"
jj = "latest"
jjui = "latest"
lazygit = "latest"
lua = "5.5"
mergiraf = "latest"
neovim = "latest"
node = "latest"
rust = "latest"
usage = "latest"
uv = "latest"
"pipx:pynvim" = "latest"

[tools.bat]
version = "latest"
postinstall = "bat --completion zsh > ~/.zsh-complete/_bat"

[tools.delta]
version = "latest"
postinstall = "delta --generate-completion zsh > ~/.zsh-complete/_delta"

[tools.dotdrop]
version = "latest"
postinstall = """
curl -fsSLo ~/.zsh-complete/_dotdrop \
    "https://raw.githubusercontent.com/deadc0de6/dotdrop/refs/tags/v${MISE_TOOL_INSTALL_PATH##*/}/completion/_dotdrop-completion.zsh"
"""

[tools.eza]
version = "latest"
postinstall = """
curl --output-dir ~/.zsh-complete -fsSLO \
    "https://raw.githubusercontent.com/eza-community/eza/refs/tags/v${MISE_TOOL_INSTALL_PATH##*/}/completions/zsh/_eza"

mkdir -p ~/.config/eza
ln -sf \
    ~/.cache/antidote/catppuccin/eza/themes/mocha/catppuccin-mocha-lavender.yml \
    ~/.config/eza/theme.yml
"""

[tools.fd]
version = "latest"
postinstall = "fd --gen-completions zsh > ~/.zsh-complete/_fd"

[tools.ipython]
version = "latest"
extras = "all"
postinstall = """
"$MISE_TOOL_INSTALL_PATH/ipython/bin/register-python-argcomplete" ipython > ~/.zsh-complete/_ipython
"""

[tools.ouch]
version = "latest"
postinstall = """
cp "$MISE_TOOL_INSTALL_PATH/completions/_ouch" ~/.zsh-complete
"""

[tools.ranger]
version = "latest"
postinstall = """
mkdir -p ~/.config/ranger/plugins
ln -sf ~/.cache/antidote/jchook/ranger-zoxide ~/.config/ranger/plugins/zoxide
"""

[tools.ratarmount]
version = "latest"
uvx_args = "--with argcomplete"
postinstall = """
"$MISE_TOOL_INSTALL_PATH/ratarmount/bin/register-python-argcomplete" ratarmount > ~/.zsh-complete/_ratarmount
"""

[tools.ripgrep]
version = "latest"
postinstall = "rg --generate complete-zsh > ~/.zsh-complete/_rg"

[tools.tldr]
version = "latest"
postinstall = """
curl -fsSLo ~/.zsh-complete/_tldr \
    "https://github.com/tealdeer-rs/tealdeer/releases/download/v${MISE_TOOL_INSTALL_PATH##*/}/completions_zsh"
"""

[tools.trash-cli]
version = "latest"
extras = "completion"
postinstall = """
cmds=(trash-empty trash-list trash-restore trash-put trash)
for cmd in ${cmds[@]}; do
    $cmd --print-completion zsh > ~/.zsh-complete/_$cmd
done
"""

[tools.tree-sitter]
version = "latest"
postinstall = "tree-sitter complete --shell zsh > ~/.zsh-complete/_tree-sitter"

[tools.yazi]
version = "latest"
postinstall = """
ya pkg install

cd "$MISE_TOOL_INSTALL_PATH"
cp */completions/{_ya,_yazi} ~/.zsh-complete
"""

[tools.zoxide]
version = "latest"
postinstall = """
curl --output-dir ~/.zsh-complete -fsSLO \
    "https://raw.githubusercontent.com/ajeetdsouza/zoxide/refs/tags/v${MISE_TOOL_INSTALL_PATH##*/}/contrib/completions/_zoxide"
"""
