#:schema https://mise.jdx.dev/schema/mise.json

[dotfiles]
"~/.mytheme.omp.json" = {}
"~/Documents/PowerShell/Microsoft.PowerShell_profile.ps1" = {}

[dotfiles."~/AppData/Local/Packages/Microsoft.WindowsTerminal_8wekyb3d8bbwe/LocalState/settings.json"]
mode = "symlink"

[dotfiles."~/.config/mise/config.windows.toml"]
source = "~/.dotfiles/mise/config.windows.toml"
mode = "symlink"

[bootstrap.hooks]
post-dotfiles = """
function winget_install($pkg, $cmd)
{
    if (!(Check-Command $cmd))
    {
        winget install --id $pkg --source winget --exact
    }
}

winget_install JanDeDobbeleer.OhMyPosh oh-my-posh
winget_install Microsoft.WindowsTerminal wt
"""
