#:schema https://mise.jdx.dev/schema/mise.json

# Remember that all entries in this global config should be valid for all
# environments/platforms

[settings]
dotfiles.root = "~/.dotfiles/rc"
dotfiles.default_mode = "copy"
unix_default_inline_shell_args = "bash -c -o errexit"
use_versions_host_track = false
windows_default_inline_shell_args = "pwsh -noni -c"
windows_powershell_no_profile = false

[shell_alias]
lg = "lazygit"
y = "yazi"

[dotfiles]
"~/.config/git/ignore" = {}
"~/.gitconfig" = {}

[dotfiles."~/.config/mise/config.toml"]
source = "~/.dotfiles/mise/config.toml"
mode = "symlink"
