git:
  paging:
    pager: delta --paging=never
customCommands:
  # Derived from https://github.com/jesseduffield/lazygit/wiki/Custom-Commands-Compendium#pushing-a-specific-commit
  - key: "P"
    command: "git push {{.SelectedRemote.Name}} {{.SelectedLocalCommit.Sha}}:{{.SelectedLocalBranch.Name}}"
    context: "commits"
    loadingText: "Pushing commit..."
    description: "Push a specific commit (and any preceding)"

  # Derived from pushing specific commit
  - key: "P"
    context: "localBranches"
    command: 'git push
      {{if eq .SelectedLocalBranch.UpstreamRemote ""}} --set-upstream {{end}}
      {{.SelectedRemote.Name}} {{.SelectedLocalBranch.Name}}'
    loadingText: "Pushing branch..."
    description: "Push a specific branch"
