#:schema https://mise.jdx.dev/schema/mise.json

[bootstrap.hooks]
pre-tools = "mkdir -p ~/.zsh-complete" # Custom zsh completions

[hooks.postinstall]
shell = "bash -c"
run = """
if [[ "$MISE_INSTALLED_TOOLS" == "[]" ]]; then exit; fi

misecompsync_up="$(echo "$MISE_INSTALLED_TOOLS" |
    mise x jq -- jq -r 'any(.[]; .name == "mise-completions-sync")')"

# If `mise-completions-sync` was upgraded, regenerate all completions as
# new ones could have been added
new_only=
if [[ "$misecompsync_up" != true ]]; then
    new_only="--new-only"
fi

mise x -- misecompsync --shell zsh "$new_only"
"""

[settings]
color_theme = "catppuccin"
lockfile = true
lockfile_platforms = ["linux-x64"]
