# See https://bugs.launchpad.net/ubuntu/+source/zsh/+bug/1800280
emulate sh -c 'source /etc/profile'

# set PATH so it includes user's private bin if it exists
if [ -d "$HOME/bin" ] ; then
    PATH="$HOME/bin:$PATH"
fi

# set PATH so it includes user's private bin if it exists
if [ -d "$HOME/.local/bin" ] ; then
    PATH="$HOME/.local/bin:$PATH"
fi

# vim: ft=zsh
