# See https://bugs.launchpad.net/ubuntu/+source/zsh/+bug/1800280
emulate sh -c 'source /etc/profile'

# Derived from Oh My Zsh pyenv plugin warning
export PYENV_ROOT="$HOME/.pyenv"
if [[ -d "$PYENV_ROOT/bin" ]]; then
    export PATH="$PYENV_ROOT/bin:$PATH"
    eval "$(pyenv init --path)"
fi

# vim: ft=zsh
