#:schema https://docs.jj-vcs.dev/latest/config-schema.json

[user]
name = "My Name"

[[--scope]]
--when.repositories = ["~/projects"]
user.email = "me@work.com"

[[--scope]]
--when.repositories = ["~/personal", "~/.dotfiles"]
user.email = "me@home.com"
