#:schema https://mise.jdx.dev/schema/mise.json

[tool_alias]
7zip = "aqua:ip7z/7zip"
clipper = "go:github.com/zyedidia/clipper/cmd/clipper"
ipython = "pipx:ipython"
mergiraf = "cargo:mergiraf"
mise-completions-sync = "cargo:mise-completions-sync"
patool = "pipx:patool"
ratarmount = "pipx:ratarmount"
tldr = "cargo:tealdeer"
tree = "conda:tree"
trash-cli = "pipx:trash-cli"
universal-ctags = "conda:universal-ctags"
xclip = "conda:xclip"
zshellcheck = "go:github.com/afadesigns/zshellcheck/cmd/zshellcheck"

[tools]
7zip = "26"
bat = "latest"
cargo-binstall = "latest"
clipper = "latest"
delta = "latest"
fd = "latest"
fzf = "latest"
go = "latest"
ipython = { version = "latest", extras = "all" }
jj = "latest"
jjui = "latest"
jq = { version = "latest", lazy = true }
lazygit = "latest"
lua = "5.5"
mergiraf = "latest"
neovim = "latest"
patool = { version = "latest", extras = "argcompletion" }
ripgrep = "latest"
node = "latest"
rust = "stable"
trash-cli = { version = "latest", os = ["linux"], extras = "completion" }
tree = "latest"
tree-sitter = "latest"
universal-ctags = "latest"
usage = "latest"
uv = "latest"
vivid = "latest"
xclip = { version = "latest", os = ["linux"] }
yazi = { version = "latest", postinstall = "ya pkg install" }
"github:jannis-baum/vivify" = "latest"
"pipx:pynvim" = "latest"

[tools.eza]
version = "latest"
postinstall = """
curl --output-dir ~/.zsh-complete -fsSLO \
    "https://raw.githubusercontent.com/eza-community/eza/refs/tags/v${MISE_TOOL_INSTALL_PATH##*/}/completions/zsh/_eza"

mkdir -p ~/.config/eza
ln -sf \
    ~/.cache/antidote/catppuccin/eza/themes/mocha/catppuccin-mocha-lavender.yml \
    ~/.config/eza/theme.yml
"""

[tools.mise-completions-sync]
version = "latest"
postinstall = "misecompsync --shell zsh"

[tools.ratarmount]
version = "1.2.3"  # Due to ratarmount#191
uvx_args = "--with argcomplete"

[tools.tldr]
version = "latest"
postinstall = """
curl -fsSLo ~/.zsh-complete/_tldr \
    "https://github.com/tealdeer-rs/tealdeer/releases/download/v${MISE_TOOL_INSTALL_PATH##*/}/completions_zsh"
"""

[tools.zoxide]
version = "latest"
postinstall = """
cp $MISE_TOOL_INSTALL_PATH/completions/_zoxide ~/.zsh-complete
"""

[tools.zshellcheck]
version = "latest"
postinstall = """
curl --output-dir ~/.zsh-complete -fsSLO \
    "https://raw.githubusercontent.com/afadesigns/zshellcheck/refs/tags/v${MISE_TOOL_INSTALL_PATH##*/}/completions/zsh/_zshellcheck"
"""

[tools."pipx:argcomplete"]
version = "latest"
lazy = true
lazy_bins = [
  "register-python-argcomplete",
  "activate-global-python-argcomplete"
]
