[tools.meson]
version = "latest"
postinstall = """
curl --output-dir ~/.zsh-complete -LO \
    "https://raw.githubusercontent.com/mesonbuild/meson/refs/tags/${MISE_TOOL_INSTALL_PATH##*/}/data/shell-completions/zsh/_meson"
"""
