[mgr]
linemode = "size"

[[plugin.prepend_previewers]]
mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip2,lzma}"
run = "ratarmount-vfs"

[opener]
extract = [
  { run = 'ya pub ratarmount-vfs --list %S', desc = "Enter Ratarmount VFS" },
]
